// Generated by Apple Swift version 4.0 effective-3.2 (swiftlang-900.0.43 clang-900.0.22.8)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_attribute(external_source_symbol)
# define SWIFT_STRINGIFY(str) #str
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name) _Pragma(SWIFT_STRINGIFY(clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in=module_name, generated_declaration))), apply_to=any(function, enum, objc_interface, objc_category, objc_protocol))))
# define SWIFT_MODULE_NAMESPACE_POP _Pragma("clang attribute pop")
#else
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name)
# define SWIFT_MODULE_NAMESPACE_POP
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR __attribute__((enum_extensibility(open)))
# else
#  define SWIFT_ENUM_ATTR
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import UIKit;
@import CoreGraphics;
@import ObjectiveC;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"

SWIFT_MODULE_NAMESPACE_PUSH("Engage")
@class UIButton;
@class UIColor;
@class NSCoder;

SWIFT_CLASS("_TtC6Engage15AlertOnboarding")
@interface AlertOnboarding : UIView
@property (nonatomic, strong) UIButton * _Null_unspecified buttonBottom;
@property (nonatomic, strong) UIView * _Null_unspecified background;
@property (nonatomic, strong) UIColor * _Nonnull colorForAlertViewBackground;
@property (nonatomic, strong) UIColor * _Nonnull colorButtonBottomBackground;
@property (nonatomic, strong) UIColor * _Nonnull colorButtonText;
@property (nonatomic, strong) UIColor * _Nonnull colorTitleLabel;
@property (nonatomic, strong) UIColor * _Nonnull colorDescriptionLabel;
@property (nonatomic, strong) UIColor * _Nonnull colorPageIndicator;
@property (nonatomic, strong) UIColor * _Nonnull colorCurrentPageIndicator;
@property (nonatomic) CGFloat percentageRatioHeight;
@property (nonatomic) CGFloat percentageRatioWidth;
@property (nonatomic, copy) NSString * _Nonnull titleSkipButton;
@property (nonatomic, copy) NSString * _Nonnull titleGotItButton;
- (nonnull instancetype)initWithArrayOfImage:(NSArray<NSString *> * _Nonnull)arrayOfImage arrayOfTitle:(NSArray<NSString *> * _Nonnull)arrayOfTitle arrayOfDescription:(NSArray<NSString *> * _Nonnull)arrayOfDescription OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (void)show;
- (void)hide;
@end


SWIFT_CLASS("_TtC6Engage14CaptivateUtils")
@interface CaptivateUtils : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6Engage6Engage")
@interface Engage : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) Engage * _Nonnull sharedInstance;)
+ (Engage * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nullable clientSecret;
@property (nonatomic, readonly, copy) NSString * _Nullable applicationId;
- (void)initializeWithAppGUIDWithApplicationId:(NSString * _Nonnull)applicationId clientSecret:(NSString * _Nonnull)clientSecret;
- (void)registerWithUserId:(NSString * _Nonnull)userId completionHandler:(void (^ _Nonnull)(NSString * _Nonnull, NSInteger, NSString * _Nonnull))completionHandler;
- (void)updateUserWithUserId:(NSString * _Nonnull)userId attribute:(NSString * _Nonnull)attribute value:(id _Nonnull)value completionHandler:(void (^ _Nonnull)(NSString * _Nonnull, NSInteger, NSString * _Nonnull))completionHandler;
- (void)sendMetricsWithCode:(NSString * _Nonnull)code;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6Engage14EngageFeatures")
@interface EngageFeatures : NSObject
- (BOOL)hasFeatureWithCode:(NSString * _Nonnull)code SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getValueForFeatureWithCode:(NSString * _Nonnull)featureWithCode variableWithCode:(NSString * _Nonnull)variableWithCode SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end



enum PMAlertActionStyle : NSInteger;

SWIFT_CLASS("_TtC6Engage13PMAlertAction")
@interface PMAlertAction : UIButton
@property (nonatomic) enum PMAlertActionStyle actionStyle;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithTitle:(NSString * _Nullable)title style:(enum PMAlertActionStyle)style action:(void (^ _Nullable)(void))action;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(NSInteger, PMAlertActionStyle) {
  PMAlertActionStyleDefault = 0,
  PMAlertActionStyleCancel = 1,
};

@class UIImageView;
@class NSLayoutConstraint;
@class UILabel;
@class UIStackView;
@class UIImage;
enum PMAlertControllerStyle : NSInteger;
@class NSBundle;

SWIFT_CLASS("_TtC6Engage17PMAlertController")
@interface PMAlertController : UIViewController
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified alertMaskBackground;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified alertView;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified alertViewWidthConstraint;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified headerView;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified headerViewHeightConstraint;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified alertImage;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified alertTitle;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified alertDescription;
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified alertActionStackView;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified alertStackViewHeightConstraint;
@property (nonatomic) CGFloat ALERT_STACK_VIEW_HEIGHT;
@property (nonatomic) BOOL gravityDismissAnimation;
- (nonnull instancetype)initWithTitle:(NSString * _Nonnull)title description:(NSString * _Nonnull)description image:(UIImage * _Nullable)image style:(enum PMAlertControllerStyle)style;
- (void)addAction:(PMAlertAction * _Nonnull)alertAction;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



typedef SWIFT_ENUM(NSInteger, PMAlertControllerStyle) {
  PMAlertControllerStyleAlert = 0,
  PMAlertControllerStyleWalkthrough = 1,
};


SWIFT_CLASS("_TtC6Engage24PopUpViewControllerSwift")
@interface PopUpViewControllerSwift : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Null_unspecified)nibNameOrNil bundle:(NSBundle * _Null_unspecified)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)showInView:(UIView * _Null_unspecified)aView withImage:(UIImage * _Null_unspecified)image withMessage:(NSString * _Null_unspecified)message animated:(BOOL)animated;
- (IBAction)closePopup:(id _Nonnull)sender;
@end


@interface UIDevice (SWIFT_EXTENSION(Engage))
@property (nonatomic, readonly, copy) NSString * _Nonnull modelName;
@end

SWIFT_MODULE_NAMESPACE_POP
#pragma clang diagnostic pop
